"""add email verification otp fields

Revision ID: 19e3678792c2
Revises: 82b41df9c326
Create Date: 2026-08-22 11:50:37.085249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19e3678792c2'
down_revision: Union[str, Sequence[str], None] = '82b41df9c326'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('otp_code', sa.String(length=6), nullable=True))
    op.add_column('users', sa.Column('otp_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'otp_expires_at')
    op.drop_column('users', 'otp_code')
    # ### end Alembic commands ###
