"""expand employee profile

Revision ID: ada296c51461
Revises: 19e3678792c2
Create Date: 2026-08-22 12:40:55.882060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ada296c51461'
down_revision: Union[str, Sequence[str], None] = '19e3678792c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('employees', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('employees', sa.Column('profile_picture', sa.String(length=500), nullable=True))
    op.add_column('employees', sa.Column('employment_status', sa.String(length=30), nullable=False))
    op.add_column('employees', sa.Column('emergency_contact_name', sa.String(length=100), nullable=True))
    op.add_column('employees', sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'emergency_contact_phone')
    op.drop_column('employees', 'emergency_contact_name')
    op.drop_column('employees', 'employment_status')
    op.drop_column('employees', 'profile_picture')
    op.drop_column('employees', 'address')
    op.drop_column('employees', 'date_of_birth')
    # ### end Alembic commands ###
